### ISSUE TITLE
Bounds on a valid Proportion?

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/demes-rs#441]
Our implementation of TryFrom<f64> for Proportion errors when the input value is 0.0.
However, the demes Python API will accept such input values.

A quick look at the spec states the following in the JSON schema:

```
  proportion:
    type: number
    exclusiveMinimum: 0
    maximum: 1
```

This issue is a reminder to consult w/the other members of the demes team...
